### ISSUE TITLE
unable to install raspi-io , 

### ISSUE THREAD

**Issue by fanzhiri** [webfansplz/vue-ssd1306#1]
(base) slakofan@slako vue-ssd1306 % npm install raspi-io       
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for raspi-io@11.0.0: wanted {"os":"any","arch":"arm,arm64"} (current: {"os":"darwin","arch":"x64"})
npm ERR! notsup Valid OS:    any
npm ERR! notsup Valid Arch:  arm,arm64
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/slakofan/.npm/_logs/2021-09-23T06_27_48_591Z-debug.log

**Comment by webfansplz** [comment]
Only Raspberry Pi is supported
